### ISSUE TITLE
Empty project space on Posit.cloud?

### ISSUE THREAD

**Issue by ads40** [dtkaplan/Lessons-in-statistical-thinking#2]
Using the link provided (https://posit.cloud/content/6532153) and creating a user account seems to result in an _empty_ project space. There are no files or project skeleton and, crucially, there are no installed packages beyond the base installation. Is this the intention?

As it is, the initial command given to be entered at the console will fail:

```
> library(LSTbook)
Error in library(LSTbook) : there is no package called ‘LSTbook’
```
New users of R will not know to install the package using `install.package("LSTbook")`.

Should this detail be included or is something going astray with the permissions/set-up of the project in Posit.cloud?

**Comment by ads40** [comment]
My comment that

> there are no installed packages beyond the base installation

is not quite right. On closer inspection, the system library within the project does contain more packages than normal, including lots of Tidyverse packages and so on. But the `{LSTbook}` package is not preinstalled.

**Comment by dtkaplan** [comment]
Thanks for pointing out this problem! I created that link months ago and
have failed to update it. I’ll fix things soon.

**Comment by dtkaplan** [comment]
I've updated the project. This includes (obviously!) installing the `{LSTbook}` package. 

Would you take another look at the project (same link as before)? I want to confirm that the fix has worked before I close this issue.

**Comment by ads40** [comment]
I have now tested this, and all is working as expected for a user starting from the blank project.

```
> library(LSTbook)

Attaching package: ‘LSTbook’

The following object is masked from ‘package:base’:

    sample

> 
```
