### ISSUE TITLE
{LSTbook} version assumed in book

### ISSUE THREAD

**Issue by homerhanumat** [dtkaplan/Lessons-in-statistical-thinking#6]
I'm considering using *Lessons in Statistical Thinking* for a course in Spring 2024, but judging from the many calls to `take_sample()` in the [book](https://dtkaplan.github.io/Lessons-in-statistical-thinking) it seems that the version of package {LSTbook} is assumed to be [this commit](https://github.com/dtkaplan/LSTbook/commit/bc2923fec3f990ad5f022af544c24975750482fa) or later, whereas the version installed in the browser by webr seems to be the earlier version 0.5.0 on CRAN.

As a result, we get errors when we run code-chunks that use `take_sample()`.

What is the anticipated time-frame for harmonizing the text of the book with a version of {LSTbook} that webr can access?

**Comment by dtkaplan** [comment]
Hi Homer,

Thanks for pointing this out. I'll update the CRAN version this week or
next. Over a week or so, that will propagate into the webr system.

Best,
Danny

-

**Comment by dtkaplan** [comment]
This is a good idea. I haven't ever set up r-universe, but I'm trying it
out following instructions for setting up a GitHub repository
dtkaplan.r-universe.dev

I'll let you know how it goes.

Best,
Danny

**Comment by homerhanumat** [comment]
I tried adding LSTbook to my own r-universe repo (see [here](https://github.com/r-universe/homerhanumat)) but as you can see the build for the latest version failed.

**Comment by homerhanumat** [comment]
And yet even though the build was reported as failed (apparently due to problems with vignettes), enough got through that one can use webr.  At any rate, it's working [here](https://github.com/homerhanumat/m337notes).  Odd.

**Comment by homerhanumat** [comment]
Looking at the github action more closely, I see that the necessary binaries did get built.  Vignettes are superflous for webr, so r-universe is a good solution.

**Comment by dtkaplan** [comment]
I just set up the r-universe repo. It was quick enough that you saw it
before I did on github.com/r-universe.

As for the build failure ... this showed up this morning when I "checked"
the package, preparing it for re-release to CRAN. But once I got r-universe
going I looked into the vignette failure, which was really a failure in an
internal function `model_type()`. That's fixed now, as is another
vignette-related problem. I have some documentation problems to fix before
re-releasing it to CRAN.

Glad to hear that the webr binaries got built. Do you know how I refer to
them in the YAML for the Quarto files?

- Danny

**Comment by homerhanumat** [comment]
I did not realize until a few days ago that one gets a nice little website for one's R-universe repository:

>[https://dtkaplan.r-universe.dev](https://dtkaplan.r-universe.dev)

**Comment by dtkaplan** [comment]
OK, the LSTbook update has been submitted to CRAN. For updates, the process
at CRAN's end is pretty automatic.

Also, I understand that r-universe will attempt another build tomorrow.
Everything should work with that.

Thanks for the good suggestion to do things via r-universe.

Also, are you interested in catching up?

- Danny

**Comment by homerhanumat** [comment]
Sure!  I'm interested to know more about your recent projects.  Send me an email and we'll set up a time to talk on Zoom or something.

**Comment by dtkaplan** [comment]
My schedule is remarkably flexible today and next week. Pick a time that's
convenient for you and I'll be there.

- Danny

**Comment by dtkaplan** [comment]
My mistake. I need to recompile the book with the r-universe.org link. I'm
working with another document derived from LST for my "quantitative
reasoning" course this semester. I added the webr:repos field there but
neglected to do so in LST.

I've just done the recompilation of LST and checked that things are
working. Hopefully they will work at your end, too!

Also, I'll arrange for the missing NHANES data frame to be put on
r-universe so that anyone can access it from webr. This will not happen
this morning, In the meantime, you can install it on your laptop from
github then pop the rda file onto a web site your students can reach.
install_github("dtkaplan/NHANES")

Thanks for your patience.

- Danny

**Comment by homerhanumat** [comment]
No worries.  And yes, it's working now.

**Comment by homerhanumat** [comment]
Our classes begin week after next.  I'm just looking ahead, choosing problems for homework, writing some of my own, etc.

**Comment by dtkaplan** [comment]
That's very helpful for me. This is my first week of teaching. Maya and I
arrived in Austin Saturday night and promptly both got a cold. Between the
new house, new job, new, city, and the cold, it's been a little stressful.
But I'll be able to catch up soon.

- Danny
